import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import GoTo from "@/components/GoTo";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col gap-4">
          {children}
          <GoTo url={'/'} text={'Go Back'}/>
        </div>
      </body>
    </html>
  );
}
